# Generated by Django 2.2.2 on 2019-06-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('ip', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('exsi_version', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'v_center',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='名称')),
                ('vmpathname', models.CharField(blank=True, max_length=128, null=True)),
                ('guestfullname', models.CharField(blank=True, max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=255, null=True)),
                ('powerstate', models.CharField(blank=True, max_length=12, null=True, verbose_name='电源状态')),
                ('ipaddress', models.CharField(blank=True, max_length=16, null=True)),
                ('des', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('numcpu', models.IntegerField(blank=True, null=True)),
                ('memorysizemb', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('vcent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VCenter')),
            ],
            options={
                'db_table': 'vms',
                'managed': True,
            },
        ),
    ]
