# Generated by Django 2.2.4 on 2019-08-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('ip', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('exsi_version', models.CharField(blank=True, max_length=16, null=True)),
                ('memory', models.IntegerField(verbose_name='内存')),
                ('available_memory', models.IntegerField(verbose_name='可用内存')),
                ('system', models.CharField(max_length=255, verbose_name='操作系统')),
                ('cpu', models.CharField(max_length=255, verbose_name='CPU信息')),
                ('disk', models.CharField(max_length=255, verbose_name='存储信息')),
            ],
            options={
                'verbose_name_plural': '宿主机',
                'db_table': 'v_center',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='名称')),
                ('vmpathname', models.CharField(blank=True, max_length=128, null=True)),
                ('guestfullname', models.CharField(blank=True, max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=255, null=True)),
                ('powerstate', models.CharField(blank=True, max_length=12, null=True, verbose_name='电源状态')),
                ('ipaddress', models.CharField(blank=True, max_length=16, null=True)),
                ('des', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('numcpu', models.IntegerField(blank=True, null=True)),
                ('memorysizemb', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='VM-uuid')),
                ('createTime', models.DateField(auto_now_add=True)),
                ('vcent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.VCenter')),
            ],
            options={
                'verbose_name_plural': '虚拟机',
                'db_table': 'vms',
                'managed': True,
            },
        ),
    ]
