# Generated by Django 2.2.4 on 2019-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcenter',
            name='available_memory',
            field=models.IntegerField(null=True, verbose_name='可用内存'),
        ),
        migrations.AlterField(
            model_name='vcenter',
            name='cpu',
            field=models.CharField(max_length=255, null=True, verbose_name='CPU信息'),
        ),
        migrations.AlterField(
            model_name='vcenter',
            name='disk',
            field=models.CharField(max_length=255, null=True, verbose_name='存储信息'),
        ),
        migrations.AlterField(
            model_name='vcenter',
            name='memory',
            field=models.IntegerField(null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='vcenter',
            name='system',
            field=models.CharField(max_length=255, null=True, verbose_name='操作系统'),
        ),
    ]
