# Generated by Django 2.2.2 on 2019-06-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vms_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='uuid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='VM-uuid'),
        ),
    ]
