# Generated by Django 2.2.4 on 2019-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190826_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcenter',
            name='available_memory',
            field=models.CharField(max_length=64, null=True, verbose_name='可用内存'),
        ),
    ]
