# Generated by Django 2.2.4 on 2019-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190826_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcenter',
            name='disk',
            field=models.TextField(null=True, verbose_name='存储信息'),
        ),
    ]
